# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://arampacha.github.io/reformer_fastai/"

git_url = "https://github.com/arampacha/reformer_fastai/tree/master/"

def custom_doc_links(name): return None
