# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/07_metrics.ipynb (unless otherwise specified).

__all__ = ['MaskedAccuracy']

# Cell
import torch

# Cell
class MaskedAccuracy:
    "Computes accuracy skipping values where targ=='ignore'"
    def __init__(self, ignore:int=-100):
        self.ignore = ignore
    def __call__(self, inp, targ):
        pred = inp.argmax(dim=-1)
        mask = targ != self.ignore
        return (pred[mask] == targ[mask]).float().mean()